# version: '3'
services:
  db:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1469
      - POSTGRES_DB=weather
    networks:
      - app-network
  app:
    build: .
    # command: bash -c "./entrypoint.sh python3 src/main.py"
    depends_on:
       - db
    networks:
      - app-network
networks:
  app-network: